---
- hosts: hosts
  sudo: yes
  user: pi

  tasks:
    - name: Create destination directory on the Pi for our key.
      file: state=directory dest=/home/pi/.ssh/

    - name: Push your RSA key to the Raspberry Pi
      copy: src=~/.ssh/id_rsa.pub dest=/home/pi/.ssh/authorized_keys owner=pi
      register: rsa
      ignore_errors: yes

    - name: Push your DSA key to the Raspberry Pi
      copy: src=~/.ssh/id_dsa.pub dest=/home/pi/.ssh/authorized_keys owner=pi
      when: rsa|failed
